num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
dataset: 20-imagenet
dataset_path: ../data
frequency_save: 0
batch_size: 64
lr: 0.005
lr_scheduler: ReduceLROnPlateau
model: preactresnet18
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 200