device: 'cuda:0'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'imagenette-320'

epochs: 130
batch_size: 64
num_workers: 4
lr: 0.005
lr_scheduler: ReduceLROnPlateau
model: 'preactresnet18'

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 0.0005
frequency_save: 0

random_seed: 0

percentile: 85
